
# import gee_time_series
import os, argparse, re
from math import cos, radians
import pandas as pd
# import ee

from shapely.geometry import Polygon
import geopandas as gpd 
import ee 
shapefile_name = "./shapefile/buffer1.shp"
shapefile = gpd.read_file(shapefile_name)
a = shapefile.to_json()

# features = []
# for i in range(shapefile.shape[0]):
    # geom = shapefile.iloc[i:i+1,:] 
    # jsonDict = eval(geom.to_json()) 
    # geojsonDict = jsonDict['features'][0] 
    # features.append(ee.Feature(geojsonDict)) 

# geometry = ee.Geometry.Polygon(features)
# geometry = ee.Geometry.Polygon(geojsonDict['geometry'])
# geometry = ee.Geometry.Polygon(geojsonDict['geometry']['coordinates'][0])

# col = ee.ImageCollection(product).\
    # select(tuple(bands)).\
    # filterDate(start_date, end_date).filterBounds(geometry)


# region = col.getRegion(geometry, int(scale)).getInfo()

# a = col.first()


# GEE subset subroutine 
def gee_subset_shape(product = None,
              bands = None,
              start_date = None,
              end_date = None,
              scale = None,
              shapefile = "./shapefile/buffer1.shp"):
    # setup the geometry, based upon point locations as specified
    # in the locations file or provided by a latitude or longitude
    # on the command line / when grow is provided pad the location
    # so it becomes a rectangle (report all values raw in a tidy
    # matrix)
    # shapefile_name = "./shapefile/buffer1.shp"
    shapefile = gpd.read_file(shapefile)
    a = shapefile.to_json()
    i=0
    geom = shapefile.iloc[i:i+1,:] 
    jsonDict = eval(geom.to_json()) 
    geojsonDict = jsonDict['features'][0] 
    # features.append(ee.Feature(geojsonDict)) 
    geometry = ee.Geometry.Polygon(geojsonDict['geometry']['coordinates'][0])
    
    # Allow for limited SAR radar product support
    if re.search("S1_GRD", product):
        # convert list to string, to play nice with listContains
        col = ee.ImageCollection('COPERNICUS/S1_GRD').\
            select(tuple(bands)).\
            filter(ee.Filter.eq('resolution_meters', int(scale))).\
            filterDate(start_date, end_date).filterBounds(geometry)
    else:
        col = ee.ImageCollection(product).\
            select(tuple(bands)).\
            filterDate(start_date, end_date)
    
    # region values as generated by getRegion
    # error trap deals with cases of a single band
    # being queried
    try:
        region = col.getRegion(geometry, int(scale)).getInfo()
    except:
        print("not a collection")
        region = ee.ImageCollection(ee.Image(product)).\
            getRegion(geometry, int(scale)).getInfo()
    
    # stuff the values in a dataframe for convenience      
    df = pd.DataFrame.from_records(region[1:len(region)])
    
    # use the first list item as column names
    df.columns = region[0]
    
    # divide the time field by 1000 as in milliseconds
    # while datetime takes seconds to convert unix time
    # to dates
    df.time = df.time / 1000
    df['time'] = pd.to_datetime(df['time'], unit = 's')
    df.rename(columns = {'time': 'date'}, inplace = True)
    df.sort_values(by = 'date')
    
    # add the product name and latitude, longitude as a column
    # just to make sense of the returned data after the fact
    df['product'] = pd.Series(product, index = df.index)
    
    # return output
    return df


# col = ee.ImageCollection('COPERNICUS/S1_GRD').\
  # filter(ee.Filter.listContains('transmitterReceiverPolarisation', sar_band)).\
  # filter(ee.Filter.eq('instrumentMode', instrument)).select(bands).\
  # filter(ee.Filter.eq('resolution_meters', int(scale))).\
  # filter(ee.Filter.eq('orbitProperties_pass', orbit)).\
  # filterDate(start_date, end_date).filterBounds(geometry)
  


# col = ee.ImageCollection(product).\
  # select(tuple(bands)).\
  # filterDate(start_date, end_date)
  


# col = ee.Image(product).\
  # select(tuple(bands))
  
# Adding a NDVI band
# def addNDVI(image):
  # ndvi = image.normalizedDifference(['SR_B5', 'SR_B4']).rename('ndvi')
  # return image.addBands([ndvi])

# col.map(addNDVI)